### ISSUE TITLE
test_square.py gatorgrade

### ISSUE THREAD

**Issue by wolff01** [ProactiveProgrammers/integer-squaring-starter#2]
Comments for test_square are not correctly worded for checking in test_square.py

**Comment by gkapfham** [comment]
Hello @wolff01, thanks so much for raising this issue!

I am writing to confirm that it was resolved correctly for this repository and, additionally, for the solution repository from which this repository was derived.

I am now going to close this issue.

You may reopen it if you think that the issue was not fully resolved.
